testsuite: fix racy job wait test
Problem: t/python/t0010-job-py occasionally fails:

  not ok 33 __main__.TestJob.test_32_job_result
  ---
    message: |
      Traceback (most recent call last):
        File "python/t0010-job.py", line 574, in test_32_job_result
          self.assertEqual(
      AssertionError: 143 != -15
  ...
  1..33

The test cancels a sleep job just after the start event appears in
the main eventlog, but at that point, _usually_ only the shell
has started, and the sleep has not yet been spawned.  When the
sleep actually does get spawned, the wait status is different than
expected.

Change the test to wait for the shell.start event in the guest.exec
eventlog before canceling, and then expect 143<<8.

Fixes #3666