python: work around missing 'exception' attribute in Flux class
Problem: The FluxExcutor `test_cancel_submit` test fails with the
error:

  not ok 5 __main__.TestFluxExecutor.test_cancel_submit
  # class = <class 'flux.core.handle.Flux'>
  # Exception in thread FluxExecutor-4-0:
  # Traceback (most recent call last):
  #  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  #    self.run()
  #  File "/home/grondo/git/f.git/src/bindings/python/flux/job/executor.py",
  #   line 76, in run
  #    self.__run()
  #  File "/home/grondo/git/f.git/src/bindings/python/flux/job/executor.py",
  #   line 98, in __run
  #    if self.__flux_handle.reactor_run() < 0:
  #  File "/home/grondo/git/f.git/src/bindings/python/flux/core/handle.py",
  #   line 290, in reactor_run
  #    Flux.raise_if_exception()
  #  File "/home/grondo/git/f.git/src/bindings/python/flux/core/handle.py",
  #   line 128, in raise_if_exception
  #    if cls.tls.exception is not None:
  # AttributeError: '_thread._local' object has no attribute 'exception'

For some reason the `tls.exception` attribute is not being initialized
for one of the FluxExecutor threads, which doesn't make sense since
it is a class attribute.

Work around the issue by using getattr() so no exception is raised if
the attribute is missing. There can be no handle exception to raise
when there's no attribute anyway.