broker: use pclose(3) after popen(3)
Problem: broker/liblist closes a `FILE *` returned from popen(3) using
fclose(3) instead of pclose(3). This results in an error on GCC 11.2:

 liblist.c:107:9: error: 'fclose' called on pointer returned from a
                  mismatched allocation function [-Werror=mismatched-dealloc]

Replace the fclose(3) with pclose(3).