explicit cast to resolve implicit cast warning
clang 15, and some of the newer GCCs as well, warn in more cases on
implicit int to float conversions that lose precision.  since UINT64_MAX
can't be represented faithfully as a double this was caught by our
warning settings.  Warning, and resulting Werror error, below:

```
 parse_size.c:116:18: error: implicit conversion from 'unsigned long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-const-int-float-conversion]
    if (result > UINT64_MAX) {
               ~ ^~~~~~~~~~
/usr/include/stdint.h:130:23: note: expanded from macro 'UINT64_MAX'
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/stdint.h:107:25: note: expanded from macro '__UINT64_C'
                        ^~~~~~~
<scratch space>:149:1: note: expanded from here
18446744073709551615UL
^~~~~~~~~~~~~~~~~~~~~~
```