python: remove package arg from trampoline import_module()
On Python 3.4, the following line in trampoline.py

  user_mod = importlib.import_module("flux.modules." + name, "flux.modules")

was generating the error:

   SystemError: Parent module 'flux.modules' not loaded,
                cannot perform relative import

Remove the package="flux.modules" argument to quiet the warning, since
import_module() is not being used here for a relative import.