python: fix exception from flux.message.msg_typestr()
Problem: When trying to use flux.message.msg_typestr(), the following
exception is raised:

  TypeError: string() argument 1 must be _cffi_backend.CData, not bytes

Do not use ffi.string() on the result from flux_msg_typestr() since
it does not seem to be required. Just decode the result.