README: add libc development packages in requirements
Problem: It has been shown that when libc6-dev is missing on a
host system, the build fails in a confusing way:

 ./ccan/endian/endian.h:112:2: error: #error "Unknown endian"
  112 | #error "Unknown endian"
      |  ^~~~~

Explicitly list that glibc development packages are requirements
to build flux-core to avoid this (and probably other) errors.

Fixes #4002