python: fix ImportError for collections.abc.Mapping
Problem: On Python 3.10, the import of Mapping from collections
gets

 "ImportError: cannot import name 'Mapping' from 'collections'"

It turns out that Mapping should be imported from 'collections.abc'
not just 'collections'. Fix the import.

Fixes #4040