ccan/base64: fix compile error on clang/ppc64le
Problem: clang 6.0+ on ppcle issues the following warning when
compiling the ccan base64 implementation:

 ccan/base64/base64.c:34:10: error: result of comparison of constant
  255 with expression of type 'int8_t' (aka 'signed char') is always
  false [-Werror,-Wtautological-constant-out-of-range-compare]

   if (ret == (char)0xff) {
       ~~~ ^ ~~~~~~~~~~

 ccan/base64/base64.c:44:57: error: result of comparison of constant 255
  with expression of type 'const signed char' is always true
  [-Werror,-Wtautological-constant-out-of-range-compare]

 return (maps->decode_map[(const unsigned char)b64char] != (char)0xff);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~

Silence these warnings by casting 0xff to int8_t instead of char.

Fixes #3874