testsuite: fix racy module trace test
Problem: occasionally one of the module trace tests
fails:

FAIL: t3401-module-trace.t 28 - kvs.lookup request was captured
ERROR: t3401-module-trace.t - exited with status 1

Add some synchronization so that we are sure the trace has
started before the desired messages are sent.

Fixes #6921