libjob: change too-large enum constant to #define
Problem: python cffi cannot translate the FLUX_JOBID_ANY
enumeration constant on a 32-bit system:

  cffi.CDefError: anonymous $enum_$19: enum $19 values don't all fit into either 'long' or 'unsigned long'

C99 only specifies that that enums are large enough to hold integer
values (c.f. C99 standard, Section 6.7.2.2: Enumeration Specifiers).
gcc seemingly allows 64-bit values, but cffi apparently does not.

Change FLUX_JOBID_ANY to a #define.

Since we are running flux headers through the C preprocessor before
cffi, also define this value in the python binding's 'cdefs'.

Add a sharness test to ensure that job.h and cdefs stay in sync.