test/doc: detect blank linkes in aspell dictionary
Problem: spaces in local dictionary can cause aspell
to silently miss spelling errors.

Check for blank lines in dictionary in "spellcheck" wrapper
script and exit with an error if one is found so that
spell checking will fail in an obvious way.

Note: aspell-0.60.7~20110 (Ubuntu 16.04.2 LTS) is silent.
The version on travis does emit an error, although tests
were still passing:

  Error: /home/travis/build/flux-framework/flux-core/
  flux-core-0.6.0-345-g9283c84/_build/../doc/test/spell.en.pws:
  The word "" is invalid. Empty string.